spring:
  datasource:
    url: jdbc:h2:mem:trello;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.insert_strategy: default
      hibernate:
        format_sql: true
server:
  port: 8080